### ISSUE TITLE
[GL] Map rendering bug omnibus

### ISSUE THREAD

**Issue by bkoropoff** [kraflab/dsda-doom#338]
- [ ] [Requiem MAP13](https://github.com/kraflab/dsda-doom/issues/338#issuecomment-1500992354) (some combination of map hole and missing bleeds)
- [ ] [Doom II MAP21](https://github.com/kraflab/dsda-doom/issues/338#issuecomment-1500992455) (mapper goof)
- [ ] [Eternal MAP28](https://github.com/kraflab/dsda-doom/issues/338#issuecomment-1500992501) (map hole)
- [ ] [BTSX E2 MAP09](https://github.com/kraflab/dsda-doom/issues/338#issuecomment-1510467166) (bounding box culling issue?)
- [ ] [BTSX E1 MAP01](https://github.com/kraflab/dsda-doom/issues/338#issuecomment-1510467780) (missing bleed)
- [ ] [KDiKDiZD MAP15](https://github.com/kraflab/dsda-doom/issues/338#issuecomment-1514010644) (missing bleeds)
- [ ] [SID MAP01](https://github.com/kraflab/dsda-doom/issues/338#issuecomment-1518683408) (missing flat bleeds, bad stencil wall bleed)
- [ ] [Scythe MAP30](https://github.com/kraflab/dsda-doom/issues/338#issuecomment-1530018268) (map hole)
- [x] [CChest2 MAP05](https://github.com/kraflab/dsda-doom/issues/338#issuecomment-1532306299) (bad stencil wall bleed)
- [ ] [Scythe 2 MAP23](https://github.com/kraflab/dsda-doom/issues/338#issuecomment-1552268992) (map hole)
- [ ] [Grove MAP01](https://github.com/kraflab/dsda-doom/issues/338#issuecomment-1558569295) (sky rendering/occlusion)
- [ ] [HR2Final MAP01](https://github.com/kraflab/dsda-doom/issues/338#issuecomment-1575029020) (missing unintentional bleed)
- [ ] [AV MAP01](https://github.com/kraflab/dsda-doom/issues/338#issuecomment-1575099899) (missing bleed)
- [ ] [SKLHALL2](https://github.com/kraflab/dsda-doom/issues/338#issuecomment-1581907571) (map hole)
- [ ] [Judgment MAP26](https://github.com/kraflab/dsda-doom/issues/338#issuecomment-1584389426) (???)

**Comment by bkoropoff** [comment]
# Requiem MAP13

![222992431-f670142d-1aef-4b47-8f15-b823a2b33a7d](https://user-images.githubusercontent.com/2101303/230745776-6054a824-20e9-45f2-9ade-09cc8197d05b.png)

**Comment by bkoropoff** [comment]
# Doom II MAP21

Thanks Sandy
![229660839-00f43b29-2311-46db-98ba-4adfebc64148](https://user-images.githubusercontent.com/2101303/230745789-714fde98-2171-4830-9c09-218656d3df7a.png)
![229660866-bd3bf132-8f1f-456c-9306-8129f4e2a832](https://user-images.githubusercontent.com/2101303/230745792-8c5ee078-6643-40ea-b4c2-4dbd76ebc660.png)

**Comment by bkoropoff** [comment]
# Eternal MAP28

![229660983-0558d5ed-f7c3-4a70-b1a4-6c48616da834](https://user-images.githubusercontent.com/2101303/230745798-72db7162-241c-45f3-84f7-57273c30de54.png)
![229660998-09e0cd46-b026-4197-9bec-04da2871619f](https://user-images.githubusercontent.com/2101303/230745801-5396820c-6caa-49df-804c-2043a20627a4.png)

**Comment by bkoropoff** [comment]
# ~~KDiKDiZD MAP15~~

This actually occurs in software, it's just not noticeable at 320x200.  It's a bug in the map.

![224461413-f79ca67d-db9d-40fc-ac1d-c5e6c5d2ff59](https://user-images.githubusercontent.com/2101303/230745811-01c9c4b8-981a-40cd-a12f-3b3669e86549.png)

**Comment by otavio-farinon** [comment]
BTSX E2 MAP09

https://user-images.githubusercontent.com/39385382/232337441-2e49383c-ceee-4fe2-a76b-77274ae792eb.mp4

**Comment by bkoropoff** [comment]
# BTSX E1 MAP01

![doom00](https://user-images.githubusercontent.com/2101303/232337568-7b13ab75-3e92-48b4-a1ae-c7c49e66ec7a.png)
![doom01](https://user-images.githubusercontent.com/2101303/232337571-c960cd62-f16f-4be1-b647-b52a0305aab7.png)

**Comment by bkoropoff** [comment]
# KDiKDiZD MAP15
![doom00](https://user-images.githubusercontent.com/2101303/232943547-8061f1de-cd5e-447e-adb1-9afa0666843c.png)
![doom01](https://user-images.githubusercontent.com/2101303/232943555-38b46d49-f860-426b-878b-ce94fd24d28a.png)

**Comment by bkoropoff** [comment]
# SID MAP01

![doom00](https://user-images.githubusercontent.com/2101303/233792624-c4f928b8-0baf-439c-8a3d-78656368142e.png)
![doom01](https://user-images.githubusercontent.com/2101303/233792623-9cdfbba7-368b-47d7-8687-843708033ab6.png)

**Comment by otavio-farinon** [comment]
### Scythe MAP30

![image](https://user-images.githubusercontent.com/39385382/235501971-fe04b020-7b34-4b4b-8920-00eb69377561.png)

**Comment by bkoropoff** [comment]
# CChest2 MAP05

![doom00](https://github.com/kraflab/dsda-doom/assets/2101303/8b7bd41b-c30a-4ee0-968f-b1a5644e3548)
![doom01](https://github.com/kraflab/dsda-doom/assets/2101303/1e899ed1-9df3-45f4-a27a-195131d00b94)

**Comment by otavio-farinon** [comment]
# **Scythe 2 MAP23**

![image](https://github.com/kraflab/dsda-doom/assets/39385382/2b22aa9d-69f6-41a2-8a46-a96307021a9d)

**Comment by bkoropoff** [comment]
# Grove MAP01

![doom00](https://github.com/kraflab/dsda-doom/assets/2101303/0f1228ff-eb87-4b3c-9443-fe55480b3e0d)
![doom01](https://github.com/kraflab/dsda-doom/assets/2101303/cdc2fb9a-45d7-419f-922f-3c97a9768f13)

**Comment by bkoropoff** [comment]
# HR2Final MAP01

![doom00](https://github.com/kraflab/dsda-doom/assets/2101303/6a77fc00-f364-405c-ad9d-d780bbf7d23a) 
![doom01](https://github.com/kraflab/dsda-doom/assets/2101303/72b13974-3a04-450a-93f6-2605a9d72b5e)

**Comment by bkoropoff** [comment]
# AV MAP01

![doom00](https://github.com/kraflab/dsda-doom/assets/2101303/04963f49-48f7-46eb-9b9c-9d3e68829779)
![doom01](https://github.com/kraflab/dsda-doom/assets/2101303/eec1bd14-11e6-4996-97e6-29581e9c46a9)

**Comment by bkoropoff** [comment]
# Stickney E1M2

![doom00](https://github.com/kraflab/dsda-doom/assets/2101303/62d7f264-7949-4dd6-9285-5579a7013fbb)
![doom01](https://github.com/kraflab/dsda-doom/assets/2101303/81ff1b19-bc31-44dd-a67c-43e486aa68f2)

**Comment by bkoropoff** [comment]
# SKLHALL2

![doom00](https://github.com/kraflab/dsda-doom/assets/2101303/62966204-a37e-4859-a8a8-a325cb4cff33)
![doom01](https://github.com/kraflab/dsda-doom/assets/2101303/2561eb63-edc2-4772-9a60-f1702c073477)

**Comment by bkoropoff** [comment]
# Judgment MAP26

![doom00](https://github.com/kraflab/dsda-doom/assets/2101303/3b8b69ae-798d-45b1-8418-fb328dbc7f9d)
![doom01](https://github.com/kraflab/dsda-doom/assets/2101303/ff9006ad-9969-4f6e-86dd-0976ff9ab598)

**Comment by kraflab** [comment]
### Hell Revealations

See https://github.com/kraflab/dsda-doom/issues/427

**Comment by otavio-farinon** [comment]
### **Cannibal MAP06**

![image](https://github.com/kraflab/dsda-doom/assets/39385382/289893f3-ef88-40b7-beba-94ea785ad638)
